### ISSUE TITLE
Colorama, eksik ' işareti düzeltmesi.

### ISSUE THREAD

**Issue by nuriacar** [yazbel/python#105]
Merhabalar,

Colorama modülü `print(Fore.RED + 'sade kırmızı yazı)` satırı sonunda ' sembolü eksikliği farkettim.

Link:
https://python-istihza.yazbel.com/Ucuncu_taraf_moduller/colorama_mod%C3%BCl%C3%BC/index.html#kullanim

hatalı kod:

```
from colorama import Fore, Back, Style, init
init(autoreset=True)
print(Fore.RED + 'sade kırmızı yazı)
print(Back.GREEN + 'Yeşil arkaplan')
print(Style.DIM + 'Python')
print(Style.RESET_ALL)
print('Tekrar normal haline döndü')
```
hatalı satır:

```
print(Fore.RED + 'sade kırmızı yazı)
#bu ifadede parantez içinde sonda yer alması gereken ' yok.
```

düzgün hali:

```
from colorama import Fore, Back, Style, init
init(autoreset=True)
print(Fore.RED + 'sade kırmızı yazı')
print(Back.GREEN + 'Yeşil arkaplan')
print(Style.DIM + 'Python')
print(Style.RESET_ALL)
print('Tekrar normal haline döndü')
```
Nuri Acar

**Comment by ismailarilik** [comment]
Teşekkürler. Bir çekme isteği (pull request) atma imkanınız var mı?

**Comment by nuriacar** [comment]
Asıl ben teşekkür ederim. Bu python kaynağı çok kıymetli. Emeği olan herkese çok teşekkürler. Pull request gönderdim.
