### ISSUE TITLE
kardiz[ilk_karakter:son_karakter:atlama_sayısı]

### ISSUE THREAD

**Issue by sefaulku** [yazbel/python#110]
kardiz[ilk_karakter:son_karakter:atlama_sayısı]

Karakter dizilerini ters çevirme bölümü olması gereken:

kardiz[ilk_karakter:son_karakterin_bir_eksiği:atlama_sayısı]

**Comment by ismailarilik** [comment]
Tam anlayamadım. Bir örnek üzerinden anlatmanız mümkün mü?

**Comment by sefaulku** [comment]
Tersten yazdırma işleminde:

>>>kardiz= "istanbul"
kardiz[0]=i
kardiz[1]=s
kardiz[2]=t
kardiz[3]=a
kardiz[4]=n
kardiz[5]=b
kardiz[6]=u
kardiz[7]=l
>>>kardiz[4:1:-1]
'nat'    --> Yazıyor.   Kaynakta ki formül "kardiz[**ilk_karakter:son_karakter:atlama_sayısı**]"

Fakat burada da gördüğümüz gibi formüle göre 'nat' yazdırmak istesek. kardiz[4:2:-1] yazmamız gerekmektedir. Yani tersten yazdırma işleminde formül kardiz[**ilk_karakter:son_karakterin_bir_eksiği:atlama_sayısı**] olmalıdır.

**Comment by ismailarilik** [comment]
İlk başta öyle görünebilir, doğru. Ancak tersten değil de normal düşünün.
Bu durumda kardiz[0,2] deyimi sadece 0. ve 1. karakteri yazdırır. Daha
önceki bölümlerde okuyucuya böyle öğretilmiştir bu. Bu durumda kullanıcı
ikinci sayının bir eksiğinin dahil olduğunu öğrenmiştir. Bu durumda tersten
yazdırmada son_karakterin_bir_eksiği ifadesi kafa karışıklığına neden
olacaktır. son_karakter denilirken zaten son karakterin bir eksiğinin dahil
olacağını kullanıcı biliyor olmalı. Ben yazarın böyle düşünüp bu şekilde
yazdığını düşünüyorum ve değişiklik yapmama taraftarıyım.

21 Nis 2020 Sal 13:34 tarihinde sefaulku <notifications@github.com> şunu
yazdı:

**Comment by sefaulku** [comment]
Tabi belirtmiş olduğunuz durum doğrudur. Fakat bir önceki bölümde yazarın öğrettiği ve çıkarmış olduğu formül "karakter_dizisi[alınacak_ilk_öğenin_sırası:alınacak_son_öğenin_sırasının_bir_fazlası]" 'dir. 

Yani aslında yazarda olayı formüle ederken son yazdırılacak karakterin bir fazlasının verilmesi gerekiğini formül içinde belirtmiştir. Aynı şekilde tersten yazdırma işlemi içinde açıklamayı yapmış fakat formüle ederken son karakter olarak belirtmiştir. 

İki konu başlığı içinde formül taslağının aynı olması gerektiğini düşünüyorum. Ya bir önceki konu başlığında ki formül yada tersten yazdırma konu başlığında ki formülün değiştirilmesi gerekmektedir. Bu şekilde kalması kafa karışıklığına sebebiyet verebilir.

**Comment by ismailarilik** [comment]
Anladım, haklısınız. Gerekli düzeltmeyi yapıp pull request göndermeniz
mümkün mü?

22 Nis 2020 Çar 13:03 tarihinde sefaulku <notifications@github.com> şunu
yazdı:

**Comment by sefaulku** [comment]
İsmail Bey, İlgili güncellemeyi yapıp pull request gönderdim. Katkıda bulunanlar bölümüne herhangi bir ekleme yapmadım. Bilginize. Teşekkürler.
