### ISSUE TITLE
Eksik karakter düzeltmesi

### ISSUE THREAD

**Issue by cenkenj** [yazbel/python#113]
Merhaba,
Bölüm 39-07 de
Aşağıdaki alıntıda `__import()` kelimesi  `__import__()` olmalıydı.
Eksik kalmış. İyi çalışmalar.

>Burada modüller adlı listedeki her öğe üzerine sırasıyla `__import()` fonksiyonunu, `dir()` fonksiyonunu ve `set()` fonksiyonunu uyguluyoruz. Daha sonra elde ettiğimiz sonucu bir liste üreteci yardımıyla liste haline getirip kümeler değişkenine atıyoruz.

**Comment by ismailarilik** [comment]
Teşekkürler. Gerekli değişikliği yapıp bir çekme isteği (pull request)
göndermeniz mümkün mü?

2 May 2020 Cmt 21:37 tarihinde cenkenj <notifications@github.com> şunu
yazdı:

**Comment by EkremDincel** [comment]
#113
