### ISSUE TITLE
range Fonksiyonu

### ISSUE THREAD

**Issue by ilhancann** [yazbel/python#139]
elif len(parola) in range(3, 8):
elif len(parola) in range(3, 9): olarak düzeltilmeli

**Comment by ismailarilik** [comment]
Geri bildirim için teşekkürler! Gerekli düzeltmeyi yapıp çekme isteği (pull request) gönderebilir misiniz?

**Comment by EkremDincel** [comment]
Bahsedilen metin donguler.rst içerisinde geçiyor.
