### ISSUE TITLE
Liste ve Demetler Kısmında Yazım Hatası

### ISSUE THREAD

**Issue by tugrlbbb** [yazbel/python#144]
İyi günler,
Açıkçası çok ufak bir yazım hatası ama yine de bildirmek istedim. Python kodundan sonraki cümlede "len() fonksiyonu liste içindeki veri tiplerinin sayısını söylüyor" yazıyor.  len() fonksiyonu liste içinde ki veri tiplerinin sayısını vermiyor. Eğer 
liste içindeki veri tiplerinin sayısını söyleseydi aşağıdaki örnekteki python kodu çalıştırılınca "1" cevabı alınacaktı. Çünkü liste sadece "string" tipi verilerden oluşuyor. Doğrusu "len() fonksiyonu liste içindeki veri sayısını söylüyor" olmalıydı. Umarım bilgi eksikliğim dolayısıyla yaptığım bir hata değildir. Teşekkürler 

[https://python-istihza.yazbel.com/listeler_ve_demetler.html#listeler]

Her ne kadar karakter dizileri ve listeler iki farklı veri tipi olsa ve bu iki veri tipinin birbirinden çok farklı yönleri ve yetenekleri olsa da, bu iki veri tipi arasında önemli benzerlikler de vardır. Örneğin karakter dizilerini işlerken öğrendiğimiz pek çok fonksiyonu listelerle birlikte de kullanabilirsiniz. Mesela karakter dizilerini incelerken öğrendiğimiz len() fonksiyonu listelerin boyutunu hesaplamada da kullanılabilir:

----------------------------------------------------------------------------------------------------------------------------------------------

>>> diller = ["İngilizce", "Fransızca", "Türkçe", "İtalyanca", "İspanyolca"]
>>> len(diller)

5

----------------------------------------------------------------------------------------------------------------------------------------------
Karakter dizileri karakterlerden oluşan bir veri tipi olduğu için len() fonksiyonu karakter dizisi içindeki karakterlerin sayısını veriyor. Listeler ise başka veri tiplerini bir araya toplayan bir veri tipi olduğu için **len() fonksiyonu liste içindeki veri tiplerinin sayısını söylüyor.**

**Comment by ismailarilik** [comment]
Şöyle bir söylem görüyorum orada:

> Karakter dizileri karakterlerden oluşan bir veri tipi olduğu için len() fonksiyonu karakter dizisi içindeki karakterlerin sayısını veriyor. Listeler ise başka veri tiplerini bir araya toplayan bir veri tipi olduğu için len() fonksiyonu liste içindeki veri tiplerinin sayısını söylüyor.

Yani listeler ve karakter dizileri için ayrılmış tanım.
