### ISSUE TITLE
Fonksiyonlar Konusundaki Bir Hata

### ISSUE THREAD

**Issue by yunuskale** [yazbel/python#148]
Fonksiyonlar konusunda "Rastgele Sayıda İsimli Parametre Belirleme" başlığında
"
Örneğin:

def fonksiyon(**parametreler):
print(parametreler)

fonksiyon(isim="Ahmet", soyisim="Öz", meslek="Mühendis", şehir="Ankara")
Bu kodları çalıştırdığımızda şöyle bir çıktı alıyoruz:

{'şehir': 'Ankara', 'isim': 'Ahmet', 'soyisim': 'Öz', 'meslek': 'Mühendis'}
"
Bu örnekte çıktı yerleri yanlış verilmiş. Yeni öğrenen birisiyim ve "acaba bu kodlar sözlüktekilerin yerini mi değiştiriyor" diye düşündüm taki deneyene kadar. Bunun dışında gerçekten pythonu en rahat anlayabildiğim yer bu site. Her şey için teşekkürler.
Katkıda Bulunanlar' a eklemek isterseniz Yunus Kale olarak ekleyebilirsiniz :)

**Comment by EkremDincel** [comment]
Evet, örnek [Python3.7 versiyonu için yanlış](https://www.python.org/dev/peps/pep-0468/) ve kitap da bu versiyon için yazılmış.

> "acaba bu kodlar sözlüktekilerin yerini mi değiştiriyor"

Python'un sözlükleri hash table veri yapısını kullanıyor. Hash table'ların eklenen ``anahtar: değer`` çiftlerinin sırasını koruma gibi bir özelliği yok. Bu durum Python'un `dict` implementasyonuna özel.

**Comment by EkremDincel** [comment]
Fixed by #150 (yanlışlıkla tekrar açmışım)
