### ISSUE TITLE
Kaçış Dizileri, Uzun Ad (\N), Düzeltme

### ISSUE THREAD

**Issue by gencharitaci** [yazbel/python#153]
Kaçış dizileri, Uzun Ad (\N) başlığı altındaki örnekte 

`>>> print("\N{LATIN CAPITAL LETTER S WITH CEDILLA}")
ş  (<= Ş olması gerekiyor.)`

![Screenshot_2020-12-29_14-15-05](https://user-images.githubusercontent.com/3070808/103280114-9b2f4380-49e0-11eb-9051-76027e5be964.png)
)

**Comment by ismailarilik** [comment]
#154
