### ISSUE TITLE
Değişkeni boş olunca çalışmayan if bloğu çalışıyormuş gibi anlatılmış.

### ISSUE THREAD

**Issue by aydinyilmaz2428** [yazbel/python#157]
**[https://python-istihza.yazbel.com/donguler.html#range-fonksiyonu](url) bölümünde şöyle denilmektedir;**

    for i in range(3):
      parola = input("parola belirleyin: ")
      if not parola:
          print("parola bölümü boş geçilemez!")
  
      elif len(parola) in range(3, 8):
          print("Yeni parolanız", parola)
          break
  
      elif i == 2:
          print("parolayı 3 kez yanlış girdiniz.",
          "Lütfen 30 dakika sonra tekrar deneyin!")
  
      else:
          print("parola 8 karakterden uzun 3 karakterden kısa olmamalı")
Burada if i == 2 kodu sayesinde for döngüsü içinde belirttiğimiz i adlı değişkenin değeri 2 olduğu anda ‘parolayı 3 kez yanlış girdiniz…’ uyarısı gösterilecektir.

 **Ancak parola değişkenini 3 kere yanlış (boş) girdiğimizde (yani i=2 olduğunda)  elif i == 2: bloğu çalışmıyor. İlk if bloğu ( if not parola) çalışıyor ve program sona eriyor.**

**Comment by ismailarilik** [comment]
Bence bir yanlışlık yok. Yazar diğer if bloklarının işlevini de anlatmış olmalı.
