### ISSUE TITLE
Hata giderme talebi

### ISSUE THREAD

**Issue by ghost** [yazbel/python#168]
input() fonksiyonu konusunda gecen,

isim = input("İsminiz nedir? ")
print("Merhaba", isim, end="!\n")

isim = input("İsminiz nedir? ") kisminda ":" eksik oldugu icin kod calismiyor. Bunu düzeltebilir misiniz? Tesekkürler.

**Comment by ismailarilik** [comment]
Neden çalışmıyor, nasıl bir hata veriyor? Dediğiniz şeyin sorun olmaması gerek, öyle bir şeye ihtiyaç yok.

**Comment by ghost** [comment]
String yani karakter dizisinin içerisinde olduğu için hata vermez eğer dışında olsaydi o zaman hata alırdı
