### ISSUE TITLE
Bitwise Operator

### ISSUE THREAD

**Issue by ghost** [yazbel/python#173]
Dostum kaynağını çok beğendim ellerine sağlık ama bitwise operatörleri hakkında birşey göremedim belkide ben bulamamışımdır.
Çünkü kitap baya kapsamlı bu konu içerikte yoksa konuyu eklemen için kaynak hazılayabilirim. Saygılarımla python'da yeniyim elimden geleni yaparım. Saygılarımla dostum

**Comment by ismailarilik** [comment]
Merhaba. Teşekkür ederiz. Kaynağın orijinal yazarı Fırat Özgül'dür. Dediğiniz gibi o bölüm olmayabilir. Ekleyebilirsiniz; çok memnun oluruz. Saygılar...

**Comment by ismailarilik** [comment]
Bu issue'yu kapatıyorum. Hazırladığınız metni pull request olarak atabilir misiniz? Katkıda bulunma ile ilgili daha fazla bilgi için CONTRIBUTING.md dosyasına bakabilirsiniz. Teşekkürler.

**Comment by ghost** [comment]
En kısa zamanda dönüş yapacağım dostum teşekkürler..

**Comment by ismailarilik** [comment]
https://github.com/yazbel/python-istihza/pull/225

**Comment by EkremDincel** [comment]
Fixed by #225
