### ISSUE TITLE
more simplified version of the simplified operators example

### ISSUE THREAD

**Issue by woosal1337** [yazbel/python#174]
[islecler.txt](https://github.com/yazbel/python-istihza/blob/master/_sources/islecler.txt)
Lines 845-863

The code below:
```
    x = int(input("Notunuz: "))

    if x > 100 or x < 0:
        print("Böyle bir not yok")

    elif x >= 90 <= 100:
        print("A aldınız.")

    elif x >= 80 <= 89:
        print("B aldınız.")

    elif x >= 70 <= 79:
        print("C aldınız.")

    elif x >= 60 <= 69:
        print("D aldınız.")

    elif x >= 0 <= 59:
        print("F aldınız.")
```

can be converted to code snippet as follows:

```
    x = int(input("Notunuz: "))

    if x > 100 or x < 0:
        print("Böyle bir not yok")

    elif x >= 90:
        print("A aldınız.")

    elif x >= 80:
        print("B aldınız.")

    elif x >= 70:
        print("C aldınız.")

    elif x >= 60:
        print("D aldınız.")

    elif x >= 0:
        print("F aldınız.")
```

the condition on the most right side does not really have anything to do with the condition. So, we can easily remove them. What are your opinions?

**Comment by woosal1337** [comment]
after the first operation for each condition, if the output returns `True`, which is equal to `1`, then for the second operation `1` will be less than for all of the `100`, `89`, `79`, `69`, and `59`. so, what is really the meaning to keep them?

**Comment by bahadiraraz** [comment]
We already know that 80 is less than 89, Why do you confuse us by giving such an example?
![image](https://user-images.githubusercontent.com/48323786/132043005-aaa9599b-ccd2-4a09-9d0d-4778f979e5d4.png)
nonsense

**Comment by ismailarilik** [comment]
Burada Türkçe konuşabiliriz, Türkçe bilmeyen kimse bu repolara bakmaz. =)

Haklısınız fakat burada yazar, koşullarda birden fazla mantıksal operatörün kullanılabileceğini belirtmeye çalışmış da olabilir. Algoritma kurma ve Python programlama dili konusunda bilgi ve tecrübesi olanlar bunun gereksiz olduğunu söyleyecektir ancak bunları yeni öğrenen biri için bu kodlar daha anlamlı olabilir. Bu sebeple bunların bu şekilde kalması taraftarıyım. Söylediklerim konusunda görüşleriniz nedir?

Teşekkürler.

**Comment by bahadiraraz** [comment]
ben kaldırılması taraftarıyım,hali hazırda python bilen birisi olarak bile gereksiz kafa karaşısıklığı yaşadım bilmeyen birisinin benden daha fazla kafakarışıklığı yaşayıp yanlış bilgilenmesi olası. mesela adam düşünebilir ki 80den büyük eşit ve 89dan küçük eşit gibi bir mantık izleyip tüm kodlarında bu mantık üzerinden gidebilir ama halbuki aslında orada ne kastedildiğini çözememiş bence gereksiz bir örnek olmasa ya da başka yerde gösterilse daha iyi olur.

**Comment by woosal1337** [comment]
@ismailarilik bey, değerli fikriniz ve öneriniz için çok teşekkür ederim. Aslında evet, öyle düşünüldüğünde kalmasi mantıklı, fakat kitabın özellikle yeni Python öğrenenler ve başlangıç seviye bir kitleye hitap ettiğini düşünürsek burada o kısım, yeni öğrenen kişiler arasında mantıksal bir hatayı da ogrenmeye tetikleyecektir. Okunduğunda gerçekten iki matematiksel işlemi de x inputu üzerinde yapıldığını okuyan kişi sansa da, maalesef ikinci kısımdaki operasyon ilk operasyonun çıktısı üzerinde yapılıyor. Issue açmanın sebebi de bu aslında. Eğer bu şekilde kalacaksa, o zaman sağdaki kısmın hangi operasyona hitap ettiğini bir not olarak düşmekte bir fayda olacağını ve bununla beraber ikinci değişilmesini istediğim kısmın da ek section olarak kitaba eklenebilecegini düşünüyorum. Fikirlerinizi alabilir miyim?

**Comment by ismailarilik** [comment]
Mantıklı. Bununla ilgili bir PR açarsanız, merge ederim. Katkıda bulunma ile ilgili olarak CONTRIBUTING.md dosyasına bakabilirsiniz.

**Comment by EkremDincel** [comment]
> after the first operation for each condition, if the output returns True, which is equal to 1, then for the second operation 1 will be less than for all of the 100, 89, 79, 69, and 59.

> Okunduğunda gerçekten iki matematiksel işlemi de x inputu üzerinde yapıldığını okuyan kişi sansa da, maalesef ikinci kısımdaki operasyon ilk operasyonun çıktısı üzerinde yapılıyor.

@woosal1337 bu doğru değil. Python'un karşılaştırma işlemlerinde [chaining](https://www.geeksforgeeks.org/chaining-comparison-operators-python/) var. Eğer sizin dediğiniz doğru olsaydı `1 < 2 <= 1` ifadesinin değeri şu adımlar sonucunda `True` olurdu:
```python
(1 < 2) <= 1
1 <= 1
True
```

Oysa ki `1 < 2 <= 1` ifadesi `1 < 2 and 2 <= 1` ile eşdeğerdir ve `False` döndürür.

**Comment by woosal1337** [comment]
@EkremDincel çok haklısınız. İlk kısımda orayı atlamış ve yanlış açıdan bakmış olabilirim. Fakat yeniden o kısımı kontrol ederseniz, Chain rule bile olsa, `x` değerinin condition içerisinde ortada değil, en solda olması sağ kısmın her zaman `True` değer döndürmesine ve yine de dolaşıp sağ tarafda yapılan işlemin boş kullanımına şahit oluyoruz eğer bana da katılırsanız. Fakat dokunduğunuz noktada çok haklısınız, ilk kez bu tarz bir Chain gördüğüm için yanlış anlamış olabilirim. Yorumunuz ve dikkatiniz için teşekkürler.

**Comment by EkremDincel** [comment]
@woosal1337 Bu örnekte gereksiz karşılaştırma işlemlerinin kullanıldığının ben de farkındayım, gördüğüm bir yanlışı dile getirdim sadece. Ben teşekkür ederim.
