### ISSUE TITLE
Django belgesinin "Üçüncü Taraf Modüller" kısmına alınması.

### ISSUE THREAD

**Issue by ismailarilik** [yazbel/python#19]

**Comment by hasaser** [comment]
Böyle bir kısım gerçekten gerekliydi.

**Comment by ismailarilik** [comment]
Şu PR ile kapatıldı: https://github.com/yazbel/python-istihza/pull/24

**Comment by ismailarilik** [comment]
@hasaser modülü diğer modüllerdeki gibi isimlendirebilir misiniz? Örneğin **django Modülü** gibi. Eğer Django kılavuzunun çevirisini yapıyorsanız, bunu bu modül başlığının altında bir başlık açarak yapabilirsiniz.

**Comment by ismailarilik** [comment]
Şu işleme ile kapatıldı: ddc809f
