### ISSUE TITLE
Django belgelendirilmesindeki resimler

### ISSUE THREAD

**Issue by hasaser** [yazbel/python#21]
Linkteki resimleri djangonun sitesinden im çekelim yoksa istihzada bulunsun mu?
https://docs.djangoproject.com/en/2.0/intro/tutorial02/#enter-the-admin-site

**Comment by ismailarilik** [comment]
Resimlerin bağlantılarını kullanmanız yeterli, mümkünse değişmeyecek bağlantıları.
