### ISSUE TITLE
Anasayfa simgesi değişmeli.

### ISSUE THREAD

**Issue by setanarut** [yazbel/python#35]
<img width="40" alt="ekran resmi 2018-11-14 14 53 55" src="https://user-images.githubusercontent.com/36481442/48481040-396de880-e81d-11e8-997e-5b6ea89fdd70.png">
şu simgenin anasayfa dönüş simgesi olduğu anlaşılmıyor, etiket simgesi sanıp hiç basmamıştım. 
sphinx temasının biraz düzeltilmesi gerek.

**Comment by ismailarilik** [comment]
Aslında biraz evi andırıyor. 😄 Bence düzeltilmesi gereksiz. Ancak siz düzeltip daha güzel bir hale getirirseniz, neden olmasın? 😄
