### ISSUE TITLE
Kılavuzdaki Noktalama hatası

### ISSUE THREAD

**Issue by logidecosorg** [yazbel/python#38]
Pdf'e göre sayfa 68 kitaba göre 56.sayfanın 3.paragrafında "-de" bağlacından sonra virgül kullanılmış.
çok güzel bir kılavuz yapanların eline sağlik.Hataların düzeltilmesi rica edilmiş.Ben de yardım etmek istedim.İyi çalışmalar.

**Comment by ismailarilik** [comment]
Şu cümleden mi bahsediyorsunuz?

> Önceki derslerde, pek üzerinde durmamış da olsak, biz Python’daki birkaç modülle zaten tanışmıştık.
