### ISSUE TITLE
Pypi linkleri güncellenmeli

### ISSUE THREAD

**Issue by hasaser** [yazbel/python#41]
Paketler konusundaki https://pypi.python.org/pypi linkleri https://pypi.org/ şeklinde düzeltilmeli.

**Comment by ismailarilik** [comment]
Olabilir. Gerçi bahsettiğiniz eski link, güncel linke yönlendiriyor ancak değiştirilmesi daha iyi tabii ki. Bununla ilgili bir çekme isteği göndermek ister misiniz?

**Comment by hasaser** [comment]
Bir iki hafta kadar meşgulüm sonrasında bunu yaparım.
