### ISSUE TITLE
Gömülü Fonksiyonlarda bulunan kırık link

### ISSUE THREAD

**Issue by coderistan** [yazbel/python#49]
Gömülü fonksiyonlar konu başlığı altında anlatılan [https://belgeler.yazbel.com/python-istihza/gomulu_fonksiyonlar.html#sorted](sorted) fonksiyonunun sonunda verilen [http://www.istihza.com/forum/viewtopic.php?f=25&t=1523 ](link) kırık. 

Neyseki bu link altındaki konu archive.org tarafından arşivlenmiş. 

https://web.archive.org/web/20161017211231/www.istihza.com/forum/viewtopic.php?f=25&t=1523

Bu durumda ya forumda yeni konu açılıp bu konuya yönlendirilmeli, ya da bu eski arşiv linkine yönlendirme yapılmalı. Sizce?

**Comment by hasaser** [comment]
Arşiv linkinin hiçbir zaman patlamayacağına inandığım ve belgelerin tekrar taşınması durumunda tekrar uğraştırmaması için kalıcı bir link olan archive.org linkinin koyulmasını öneriyorum.

**Comment by hasaser** [comment]
Bunu orada vermek belgeyi raz karıştıracaktır. Çünkü zaten ikinci bölümde anlatılıyor:
https://belgeler.yazbel.com/python-istihza/Ucuncu_taraf_moduller/django_mod%C3%BCl%C3%BC/django_2.html#modellerin-aktiflestirilmesi

**Comment by coderistan** [comment]
Sanırım yanlış yerde cevap verdiniz, pull request kısmında yazmanız gerekti :)

**Comment by ismailarilik** [comment]
@coderistan arşiv linki uygun, PR gönderir misiniz?
