### ISSUE TITLE
Django beşinci belge

### ISSUE THREAD

**Issue by hasaser** [yazbel/python#53]
Beşinci belgede testleri anlatıyor. Sitede daha normal testler için belge yokken Django için testleri anlatmak biraz ağır olmaz mı? Zaten ben de test yazmayı bilmiyorum. O yüzden bu belgeleri daha sonra yazmak istiyorum.

Belgenin linki: https://docs.djangoproject.com/en/2.1/intro/tutorial05/

**Comment by ismailarilik** [comment]
Bence şimdi yazın. Testler önemlidir. Belki birileri bunu görüp Python'daki `unittest` modülünü anlatmaya heveslenebilir.

**Comment by hasaser** [comment]
Tamam öyle yapayım.
