### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by HakanDemiral-zz** [yazbel/python#59]
Yeni öğrenenler için konuların altındaki disqus yorumları ve orada yazılan kodlar ilham oluyor fakat localde derlediğimiz hallerinde disqus yok, eklenemez mi?

**Comment by ismailarilik** [comment]
Emin değilim. Local'de Disqus'a neden ihtiyacınız oluyor ki?

9 Haz 2019 Paz 01:43 tarihinde Hakan Demiral <notifications@github.com>
şunu yazdı:

**Comment by hasaser** [comment]
Disqus yorumları kendi sunucularında tutuyor. O yüzden biraz zorlayabilir.
