### ISSUE TITLE
Düzeltme

### ISSUE THREAD

**Issue by Ksenofanex** [yazbel/python#67]
https://belgeler.yazbel.com/python-istihza/etkilesimli_python.html 

Yukardaki linkte Etkileşimli Python bölümünün Etkileşimli Kabuğun Hafızası kısmında;

"Burada _ komutunun değeri bir önceki işlemin sonucu olan 56715 değeri olduğu için, _ komutuna 15 eklediğimizde 56715 değerini elde ediyoruz."

Olarak yazılmış ama doğrusu şöyle olacak:

"Burada _ komutunun değeri bir önceki işlemin sonucu olan "56700" değeri olduğu için, _ komutuna 15 eklediğimizde 56715 değerini elde ediyoruz."

**Comment by coderistan** [comment]
Eğer düzeltme şansınız varsa siz düzeltip PR gönderir misiniz? Böylece projeye katkı yapanların sayısı 1 kişi artmış olur.

**Comment by Ksenofanex** [comment]
@coderistan Nasıl düzelteceğimi bilmiyorum, gösterirseniz kendim düzeltmek isterim.

**Comment by coderistan** [comment]
> @coderistan Nasıl düzelteceğimi bilmiyorum, gösterirseniz kendim düzeltmek isterim.

Aşağıdaki yazıları okuyup bir fikir edinebilirsiniz. Bir sorunuz olursa tekrar yazın

https://medium.com/@noteCe/github-ile-fork-ve-pull-request-be6077342834
https://medium.com/@cengizhanc/github-ile-açık-kaynak-projelere-katkıda-bulunmak-8a0d79090546

Kısaca, proje sayfasına geliyorsunuz ve sağ üst köşede bulunan fork butonuna basıyorsunuz. Sonra projenin bir kopyası sizin hesabınızda oluşturuluyor. Siz kendi hesabınızda bulunan kopyada birtakım değişiklikler yapıyorsunuz ve sonra pull request ile değiştirilmiş kopyayı, asıl projenin bulunduğu hesaba birleştirme isteği ile göndermiş oluyorsunuz.

**Comment by Ksenofanex** [comment]
@coderistan Gönderdim.

**Comment by coderistan** [comment]
@Ksenofanex  teşekkürler elinize sağlık. İsmail hocam gördüğü zaman onaylayacaktır. İyi günler :)

**Comment by Ksenofanex** [comment]
@coderistan Ben teşekkür ederim ilginiz ve yardımınız için, iyi günler. :)

**Comment by Ksenofanex** [comment]
@coderistan https://belgeler.yazbel.com/python-istihza/input.html#int

GitHub'daki belgeler arasında yukarıda attığım linkteki yazıyı bulamadım.

**Comment by coderistan** [comment]
@Ksenofanex input.rst dosyasında int() bölümüne bakabilirsiniz

https://github.com/yazbel/python-istihza/blob/master/sphinx_source/input.rst#int

**Comment by Ksenofanex** [comment]
@coderistan Her seferinde yaptığım değişiklikler farklı isimle kaydoluyor ve ayrıyetten pull request yapmak zorunda kalıyorum. Tahmin ediyorum ki yaptığım yanlış, hepsini "master" kaynağından yapmalıydım. Nasıl yapabilirim bunu? Mesela ilk yaptığım değişiklikler "master" kaynağına kayıtlıyken diğerlerin "patch1", "patch3" gibi isimlerle kayıtlı.

**Comment by coderistan** [comment]
@Ksenofanex öncelikle yaptığınız değişiklikleri ayrı ayrı pullrequest olarak göndermek yerine, hepsini tek seferde göndermeniz daha iyi olur. Branch konusuna gelince, aşağıdaki sayfadan yardım alabilirsiniz

https://github.com/vigo/git-puf-noktalari/blob/master/bolum-02/branch-leri-birlestirmek.md
https://git-scm.com/book/tr/v1/Git-te-Dallanma-Dallanma-ve-Birleştirmenin-Temelleri

**Comment by ismailarilik** [comment]
@coderistan'ın söylediklerine ek olarak şunu söylemek isterim. Eğer bir
PR'da tüm değişiklikleri tek seferde gönderemiyorsanız, aynı branch'e
tekrar commit atmayı deneyebilirsiniz. Bu commit'ler aynı PR'da görünür.
GitHub web arayüzünü kullanarak bunu yapmanız mümkün değil bildiğim
kadarıyla. Önce repoyu bilgisayarınıza pull edin, daha sonra ilgili
branch'e geçip commit'lerinizi push edin. Bu bilgi PR sayfalarının altında
da yazar.

30 Tem 2019 Sal 14:46 tarihinde Ksenofanex <notifications@github.com> şunu
yazdı:

**Comment by Ksenofanex** [comment]
@ismailarilik Bu şekilde merge etmeniz mümkün değil mi? Bundan sonrakileri dediğiniz şekilde yapsam?

**Comment by ismailarilik** [comment]
@Ksenofanex olur.
