### ISSUE TITLE
Hata Bildirme E-maili

### ISSUE THREAD

**Issue by coderistan** [yazbel/python#71]
https://belgeler.yazbel.com/python-istihza/katkida_bulunanlar.html

Yukarıdaki sayfada, görülen hataların ozgulfirat@gmail.com adresine iletilmesi bildirilmiş. Yazbel için böyle bir e-mail adresi var mıdır?

**Comment by ismailarilik** [comment]
Yok, e-posta yanlış. Düzeltirim. Bilgilendirme için teşekkür ederim.

30 Tem 2019 Sal 13:31 tarihinde coderistan <notifications@github.com> şunu
yazdı:

**Comment by coderistan** [comment]
Tamamdır

**Comment by EkremDincel** [comment]
Hala [düzeltilmemiş](https://python-istihza.yazbel.com/katkida_bulunanlar.html) sanırım.

**Comment by ismailarilik** [comment]
Düzeltildi.

17 Ara 2019 Sal 21:03 tarihinde EkremDincel <notifications@github.com> şunu
yazdı:
