### ISSUE TITLE
Yazım Düzeltme (Paket İçe Aktarma)

### ISSUE THREAD

**Issue by bilmuallim** [yazbel/python#74]
https://belgeler.yazbel.com/python-istihza/paketler.html#import-paket

bağlantısında **import paket** başlığı altında aşağıdaki ifade yazıyor;

_...Mesela **urllib paketini** ele alalım. Tıpkı os modülünde yaptıgımız gibi, **urllib modülünü** de su
sekilde içe aktarabiliriz:
`>>> import urllib`
Ancak os modülünün aksine, **urllib paketini** içe aktardıgımızda mevcut isim alanına herhangi
bir nitelik veya metot otomatik olarak aktarılmaz. Örnegin os modülünü içe aktardıgımızda
bu modülün içeriginin, os öneki altında mevcut isim alanına döküldügünü biliyoruz:..._

Yukarıda koyu olarak işaretlediğim urllib paketi ifadesi kullanıldıktan sonra urllib modülü olarak tekrar telaffuz edilmiş. Sonrasında tekrar urllib paketi denmiş. urllib modülü ifadesi yanlışlıkla kullanılmış diye düşünüyorum. O kısım biraz kafa karıştırıcı olmuş.

Projeye destek vermek istedim :D

**Comment by ismailarilik** [comment]
Haklısınız. PR göndererek katkıda bulunmak ister misiniz?

6 Ağu 2019 Sal 07:32 tarihinde ogretMAN <notifications@github.com> şunu
yazdı:

**Comment by bilmuallim** [comment]
Github'u ilk kez kullanıyorum. PR göndermeye çalıştım umarım doğru yapmışımdır.
