### ISSUE TITLE
Loop-else

### ISSUE THREAD

**Issue by Ksenofanex** [yazbel/python#84]
For-else ve while-else gibi konulara değinmeyecek misiniz?

**Comment by ismailarilik** [comment]
Belgeler tek bir kişi tarafından değil, bir topluluk tarafından geliştirilmekte. Eğer bir konuda bilginiz varsa, belgelere katkıda bulunabilirsiniz. Eğer bir konuda bilginiz yok ve bilgi sahibi olmak istiyorsanız, isteğinizi forum.yazbel.com'da açacağınız bir gönderide belirtirseniz, yardım etmek isteyen birisi çıkacaktır.
