### ISSUE TITLE
End parametresinde end="."konulduğunda alt satıra geçiyor.

### ISSUE THREAD

**Issue by Ers0yunus08** [yazbel/python#89]
>>> print("Bugün günlerden Salı", end=".") Bu kodun çalıştırıldığında ">>>" işareti kodun yanından devam etmesi gerekirken alt satıra geçiyor.
fakat 06/02 end konusunda işaretin kodun yanından devam etmesi gerekiyordu.

**Comment by ismailarilik** [comment]
Etkileşimli kabuğun davranışından kaynaklanıyor olabilir.
