### ISSUE TITLE
Belgelerin AsciiDoc sözdizimine çevrilmesi

### ISSUE THREAD

**Issue by ismailarilik** [yazbel/python#9]
[YazBel belgeleri]'ni AsciiDoc sözdizimi kullanarak yazıyor, [Asciidoctor] kullanarak derliyoruz. Buradaki belgelerin de Asciidoctor'a çevrilmesi belgelerdeki tutarlılık açısından iyi olacaktır. Bu konuda yardımcı olabilecek birine ihtiyacımız var.

[YazBel belgeleri]: https://github.com/yazbel/belgeler
[Asciidoctor]: https://asciidoctor.org/

**Comment by hasaser** [comment]
Bu işi bir script yazarak halledemez miyiz?

**Comment by ismailarilik** [comment]
@hasaser mümkün. Öncesinde hazır araçları araştırmak daha mantıklı.

**Comment by ismailarilik** [comment]
İptal edildi. reStructuredText ve Sphinx üzerinden ilerlemek bu belge için daha mantıklı.
