### ISSUE TITLE
lisans hakkında soru

### ISSUE THREAD

**Issue by setanarut** [yazbel/python#92]
lisans şartlarını okudum,  şunları anlayamadım. 

- Atıf yaparken bu reponun sahibine mi (ismailarilik) yoksa fırat özgül'e mi atıf yapılacak? katkı sağlayan herkesi yazmak zorunlu mu?

- içeriklerde eksiltme sadeleştirme yapılabilir mi?

**Comment by ismailarilik** [comment]
Asıl olarak Fırat beye atıf yapmalısınız. Belgenin asıl sahibi o. Bunun
dışında "Katkıda Bulunanlar" bölümüne bağlantı verirseniz, belgeye katkıda
bulunmuş olanlara da atıfta bulunmuş olursunuz.

Belgelerde istediğiniz değişikliği yapabilirsiniz. Sadece yaptığınız
değişikliği belirtmelisiniz.

20 Eki 2019 Paz 00:38 tarihinde Hazar <notifications@github.com> şunu yazdı:
