### ISSUE TITLE
Rst syntax hataları

### ISSUE THREAD

**Issue by setanarut** [yazbel/python#93]
Merhaba, bu dökümanları [Docsify](https://github.com/docsifyjs/docsify/) ortamına taşımaya karar vermiştim. [Pandoc](https://pandoc.org) ve [rst_to_md](https://github.com/sixty-north/rst_to_md)  ile rst dosyalarını markdown'a dönüştürürken dosyalarda syntax hataları olduğunu farkettim. bir örnek üzerinden açıklayayım;

# tablolar
ikili_dosyalar.rst;  bu tabloda satır başlarında 4 boşluk ve tablo hücrelerindei boşluklar olduğu için  [Pandoc](https://pandoc.org) tarafından `block quote`olarak yorumlanıyor ve çıktının hatalı olmasına sebep oluyor.
```
    ==================  ===============================================
        Etiket                  Anlamı
    ------------------  -----------------------------------------------
     /Creator             Belgeyi oluşturan yazılım
     /Producer            Belgeyi PDF'e çeviren yazılım
     /Title               Belgenin başlığı
     /Author              Belgenin yazarı
     /Subject             Belgenin konusu
     /Keywords            Belgenin anahtar kelimeleri
     /CreationDate        Belgenin oluşturulma zamanı
     /ModDate             Belgenin değiştirilme zamanı
    ==================  ===============================================
```
doğrusu şu şekilde olmalı
```
==================  ===============================================
    Etiket                  Anlamı
------------------  -----------------------------------------------
/Creator            Belgeyi oluşturan yazılım
/Producer           Belgeyi PDF'e çeviren yazılım
/Title              Belgenin başlığı
/Author             Belgenin yazarı
/Subject            Belgenin konusu
/Keywords           Belgenin anahtar kelimeleri
/CreationDate       Belgenin oluşturulma zamanı
/ModDate            Belgenin değiştirilme zamanı
==================  ===============================================
```

#  Yorumlanır metinler (interpreted-text)

ikili_dosyalar.rst; Örnek metin;

```
İkili bir dosyayı `'rb'` (veya `'wb'`, `'ab'`, `'xb'`, vb.) gibi
bir kipte açtığınızda Python satır sonlarına herhangi bir değiştirme-dönüştürme
işlemi uygulamaz.
```

Belgelerde yoğun şekilde ters tek tırnak işaretine alınmış [interpreted-text](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text) denilen kelimeler var ve olmaması gereken yerlerde kullanılmış,  bu referansların  **rolü**(role)  aşağıdaki gibi belirtilmediği için pandoc tarafından hatalı yorumlanıyor.

Bir rol işaretleyicisi iki nokta üst üste, rol adı ve başka bir iki noktadan oluşur.
```
`interpreted text`:role:
```

**'rb'** satır içi kod olduğu için rst synaxına göre çift tırnak olarak yazılmalıydı şu şekilde: 

```
İkili bir dosyayı ``'rb'`` (veya ``'wb'``, ``'ab'``, ``'xb'``, vb.) gibi
bir kipte açtığınızda Python satır sonlarına herhangi bir değiştirme-dönüştürme
işlemi uygulamaz.
```

başka bir hatalı kullanım örneği (ikili_dosyalar.rst);

```
O halde hemen önümüze bir `PDF` dosyası alalım
```
vurgula isminde rol olduğunu varsayarsak şu şekilde olmalı;

```
O halde hemen önümüze bir `PDF`:vurgula: dosyası alalım
```

şimdilik bu kadar, eğer Docsify ortamına taşıma işi ilginizi çektiyse yardımlaşma ile Markdown'a dönüştürme projesi açılabilir. ya da kendi çabalarımla da devam edebilirim. teşekkürler.

**Comment by ismailarilik** [comment]
Açıkçası belgelerin orijinal sözdizimleriyle devam etmesinden yanayım.
Zaten Python camiasında belgelendirmede genellikle reStructuredText
kullanılıyor.

20 Eki 2019 Paz 16:30 tarihinde Hazar <notifications@github.com> şunu yazdı:

**Comment by hazar-e** [comment]
sorun reStructuredText kullanılmasında değil. sayfaların standalone formatta yazılmamış olması, sphinix'e hapsedilmiş durumda. belgeler büyüyor teknoloji gelişiyor ama belgeler 90lar da takılı kalmış. taşınabilirlik sıfır.
