### ISSUE TITLE
For Döngüsünü Anlamak İçin Yapılan Son Örneğe Bakış 

### ISSUE THREAD

**Issue by 1985r** [yazbel/python#95]
```
tr_harfler = "şçöğüİı"

parola = input("Parolanız: ")

for karakter in parola:
    if karakter in tr_harfler:
        print("parolada Türkçe karakter kullanılamaz")

```
**Bu kodda eğer kullanıcı parolası içinde birden fazla türkçe karakter kullandıysa, kaç tane kullandığına bağlı olarak o kadar sayıda "parolada Türkçe karakter kulanılamaz" çıktısı veriyor. Belki de amaç buydu tam bilemiyorum. Yani parolamı öğün olarak girdiğimde 3 tr karakter olduğu için 3 kere "parolada Türkçe karakter kulanılamaz"  çıktısını veriyor. Bu kodu tek bir uyarı çıktısı verecek şekilde ayarlamak daha akla yatkın gözüküyor. Sonuçta hiçbir uygulamada yapılan hata sayısı kadar hata çıktısı verilmez. Tek bir çıktı yeterlidir. Bunu sağlamak için ek bir kod yazılabilir diye düşündüm. Bunu belirtmek istedim. Pythonda daha yeni sayılırım, bu konu dikkatimi çekti. Yanlış düşünmüş de olabilirim, sadece paylaşmak ve bildirmek istedim. Teşekkürler.**``

**Comment by ismailarilik** [comment]
Güzel bir tespit. Burada bir kere yazma ya da karakter sayısı kadar yazma ile ilgili bir düşünce olduğunu sanmıyorum. Burada anlatılmak istenen şey başka bir şey. Eğer yazar bahsettiğiniz gibi bir kod yazmaya çalışsaydı, asıl amacından sapmış olurdu. Ancak tabi siz bu kodun bahsettiğiniz gibi daha doğru çalışması için gereken değişikliği yapmaya uğraşarak kendinizi geliştirebilirsiniz.
